create table products (
	id bigint generated by default as identity primary key,
	name text not null,
	price numeric(10, 2) not null constraint price_is_positive check(price >= 0),
	stock integer not null constraint stock_is_positive check(stock >= 0),
	created_at timestamptz default now()
);
